### PR TITLE
Add Memcached support

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
I did not add a benchmark because it was not working on my machine and I could not figure out why. Tests passed anyways.
It seems to work. Thanks for the project! :)

**Comment by greyblake** [comment]
@mauricioabreu Super! Thank you for the pull request:) Now we have 5 backends:)

**Comment by greyblake** [comment]
@mauricioabreu It looks like there is something wrong with library https://github.com/comandeo/crystal-memcached
It is extremally slow... 100 inserts takes about 10 seconds. I've tried a ruby implementation, it works like it should, so the problem is somewhere in crystal client implementation

**Comment by mauricioabreu** [comment]
I am sorry for this! I thought it was a problem with my setup. I will benchmark crystal memcached soon.

**Comment by greyblake** [comment]
@mauricioabreu No worries. I am opening issue for crystal-memcached )

**Comment by greyblake** [comment]
@mauricioabreu Opened an issue: https://github.com/comandeo/crystal-memcached/issues/4

**Comment by mauricioabreu** [comment]
Thanks @greyblake !

**Comment by mauricioabreu** [comment]
Attempt to solve the problem: https://github.com/comandeo/crystal-memcached/pull/5

**Pull request merged**
